---

- name: garantindo que o unzip esteja instalado
  yum:
    name: unzip
    state: present

- name: obtendo a lista de pacotes instalado
  package_facts:
    manager: auto

- name: setando o pacote docker caso exista
  set_fact:
    docker_ce: "{{ ansible_facts.packages['docker-ce'] }}"
    docker_ee: "{{ ansible_facts.packages['docker'] }}"
    docker_pkg: "{% if (docker_ce is defined and docker_ce | length > 0) or (docker_ee is defined and docker_ee | length > 0) %}true{% else %}false{% endif %}"

- name: copia o arquivo compose file do registrator
  template:
    src: registrator-compose.j2
    dest: '{{ path_consul }}/registrator.yml'
    owner: '{{ sys_user }}'
  when: docker_pkg
