---

- name: garantindo que o unzip esteja instalado
  yum:
    name: unzip
    state: present

- name: obtendo a lista de pacotes instalado
  package_facts:
    manager: auto

- name: setando vars pacote docker e nginx caso exista
  set_fact:
    docker_ce: "{% if ansible_facts.packages['docker-ce'] is defined %}{{ ansible_facts.packages['docker-ce'] }}{% endif %}"
    docker_ee: "{% if ansible_facts.packages['docker'] is defined %} {{ ansible_facts.packages['docker'] }} {% endif %}"
    nginx_ins: "{% if ansible_facts.packages['nginx'] is defined %}{{ ansible_facts.packages['nginx'] }}{% endif %}"

- name: setando vars de pacotes instalados
  set_fact:
    docker_pkg: "{% if (docker_ce is defined and docker_ce | length > 0) or (docker_ee is defined and docker_ee | length > 0) %}true{% else %}false{% endif %}"
    nginx_pkg: "{% if nginx_ins is defined and nginx_ins | length > 0 %}true{% else %}false{% endif %}"

- name: debug
  debug:
    msg: "{% if nginx_pkg %}Srv NGINX: será instalado o consul template{% elif docker_pkg %}Srv DOCKER: será instalado o registrator{% else %}Esse servidor não tem instalado o docker nem o nginx{% endif %}"

- name: copia o arquivo compose file do registrator
  template:
    src: registrator-compose.j2
    dest: '{{ path_consul }}/registrator.yml'
    owner: '{{ sys_user }}'
  when: docker_pkg
