---

- set_fact:
    bin_consul: '{{ path_consul }}/consul_v1.2.2'
    bin_consul_cons: '{{ path_consul }}/consul'
    bin_consul_sys: '/usr/local/bin/consul'
    path_consul_json: '{{ path_consul }}/config/config.json'

- name: garantinho que o path do consul seja criado
  file:
    path: '{{ path_consul }}'
    state: directory
    owner: '{{ sys_user }}'
    mode: 0750

- name: descompactando o arquivo consul
  unarchive:
    src: '{{ _link_consul }}'
    dest: '{{ path_consul }}/'
    owner: '{{ sys_user }}'

- file: src={{ bin_consul_cons }} dest={{ bin_consul }}

- name: criando o link simbolico
  file:
    src: '{{ bin_consul }}'
    dest: '{{ item }}'
    owner: '{{ sys_user }}'
    state: link
  with_items:
    - '{{ bin_consul_cons }}'
    - '{{ bin_consul_sys }}'

- name: garantindo que o diretorio config e data estejam criados
  file:
    path: '{{ item }}'
    state: directory
    mode: 0750
    owner: '{{ sys_user }}'
  with_items:
    - '{{ path_consul }}/data'
    - '{{ path_consul }}/config'

- name: adicionando o arquivo JSON de configuracao
  template:
    src: config.json.j2
    dest: '{{ path_consul_json }}'
    owner: '{{ sys_user }}'
    mode: 0750

- name: adicionando arquivo consul.service
  template:
    src: consul-service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
  notify:
    - habilitando consul

- debug:
    msg: "ANTES DE INICIAR O CONSUL, VERIFIQUE AS CONFIGURAÇÕES EM {{ path_consul_json }}"
