---

- name: setandos as vars para instalacao do consul-template
  set_fact:
    bin_consul: '{{ path_consul }}/consul-template'
    bin_consul_sys: '/usr/local/bin/consul-template'
    path_consul_json: '{{ path_consul }}/config/options'

- name: criando diretorio para o consul-template
  file:
    path: '{{ path_consul }}'
    state: directory
    owner: '{{ sys_user }}'
    mode: 0750

- name: descompactando o pacote do consul-template
  unarchive:
    src: '{{ _link_consul_template }}'
    dest: '{{ path_consul }}/'
    owner: '{{ sys_user }}'
    remote_src: true

- name: criando link simbolico do binario do consul-template
  file:
    src: '{{ bin_consul }}'
    dest: '{{ bin_consul_sys }}'
    owner: '{{ sys_user }}'
    state: link

- name: garantindo que os diretorios de configuracao e data estejam criados
  file:
    path: '{{ item }}'
    state: directory
    mode: 0750
    owner: '{{ sys_user }}'
  with_items:
    - '{{ path_consul }}/data'
    - '{{ path_consul }}/config'
    - '{{ path_nginx }}{{ path_nginx_config }}'

- name: adicionando o arquivo exemplo de configuração do consul-template
  template:
    src: options-consul.j2
    dest: '{{ path_consul_json }}'
    owner: '{{ sys_user }}'
    mode: 0750

- name: adicionando o arquivo location.template do nginx
  copy:
    src: location.template
    dest: "{{ path_nginx }}{{ path_nginx_config }}/location.template"
    owner: '{{ sys_user }}'
    mode: 0750
  changed_when: false

- name: adicionando o arquivo upstream.template do nginx
  copy:
    src: upstream.template
    dest: "{{ path_nginx }}{{ path_nginx_config }}/upstream.template"
    owner: '{{ sys_user }}'
    mode: 0750
  changed_when: false

- name: garantindo que os arquivos location e upstream esteja criados
  file:
    path: "{{ item }}"
    state: touch
    mode: 0764
  with_items:
    - "{{ path_nginx }}{{ path_nginx_config }}/{{ name_upstream }}.conf"
    - "{{ path_nginx }}{{ path_nginx_config }}/{{ name_location }}.conf"
  changed_when: false

- name: alterando o datacenter of files
  replace:
    path: '{{ item }}'
    regexp: 'youtag'
    replace: '{{ datacenter_consul }}'
  with_items:
    - "{{ path_nginx }}{{ path_nginx_config }}/location.template"
    - "{{ path_nginx }}{{ path_nginx_config }}/upstream.template"
  changed_when: false

- name: adicionando o arquivo de nginx modelo
  template:
    src: nginx.conf.j2
    dest: "{{ path_nginx }}/nginx.conf_consul"
    mode: 0764

- name: adicionando o arquivo consul-template.service
  template:
    src: consul-template-service.j2
    dest: /etc/systemd/system/consul-template.service
    owner: root
  notify:
    - habilitando consul-template

- name: antes de iniciar
  debug:
    msg: "ANTES DE INICAR O CONSUL-TEMPLATE, VERIFICE AS CONFIGURAÇÕES DO ARQUIVO {{ path_consul_json }}"
