- set_fact:
    bin_consul: '{{ path_consul }}/consul-template_v0.19.5'
    bin_consul_cons: '{{ path_consul }}/consul-template'
    bin_consul_sys: '/usr/local/bin/consul-template'
    path_consul_json: '{{ path_consul }}/config/options'

- name: criando diretorio para o consul
  file:
    path: '{{ path_consul }}'
    state: directory
    owner: '{{ sys_user }}'
    mode: 0750
  become: yes

- name: descompactando o pacote do consul
  unarchive:
    src: '{{ _link_consul_template }}'
    dest: '{{ path_consul }}/'
    creates: '{{ bin_consul }}'
    owner: '{{ sys_user }}'
  become: yes

- name: criando link simbolico do binario do consul
  file:
    src: '{{ bin_consul }}'
    dest: '{{ item }}'
    owner: '{{ sys_user }}'
    state: link
  with_items:
    - '{{ bin_consul_cons }}'
    - '{{ bin_consul_sys }}'
  become: yes

- name: criando os diretorios de configuracao e data
  file:
    path: '{{ item }}'
    state: directory
    mode: 0750
    owner: '{{ sys_user }}'
  with_items:
    - '{{ path_consul }}/data'
    - '{{ path_consul }}/config'
  become: yes

- name: adicionando o arquivo exemplo de configuração do consul
  template:
    src: options-consul.j2
    dest: '{{ path_consul_json }}'
    owner: '{{ sys_user }}'
    mode: 0750
  become: yes

- name: adicionando o arquivo location.template do nginx 
  copy:
    src: location.template
    dest: "{{ path_nginx }}{{ path_nginx_config }}/location.template"
    owner: '{{ sys_user }}'
    mode: 0750
  become: yes

- name: adicionando o arquivo upstream.template do nginx
  copy:
    src: upstream.template
    dest: "{{ path_nginx }}{{ path_nginx_config }}/upstream.template"
    owner: '{{ sys_user }}'
    mode: 0750
  become: yes

- name: adicionando o arquivo consul-template.service
  template:
    src: consul-template-service.j2
    dest: /etc/systemd/system/consul-template.service
    owner: root
  notify:
    - habilitando consul-template 
  become: yes

- debug:
    msg: "ANTES DE INICAR O CONSUL-TEMPLATE, VERIFICE AS CONFIGURAÇÕES DO ARQUIVO {{ path_consul_json }}"
