---

- include: config.yml
  tags:
    - consul
    - consul-template
    - conf

- include: consul.yml
  become: true
  tags:
    - consul

- include: consul-template.yml
  when: nginx_pkg
  become: true
  tags:
    - consul-template
